name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git identity
        run: |
          git config --global user.name "balajiudayagiri"
          git config --global user.email "balu.udy@gmail.com"

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Debugging Output
        run: echo "Deploy step is about to run"
        
      - name: List dist directory
        run: ls -al build
      - name: Push to GitHub
        run: |
          git remote set-url origin https://balajiudayagiri:${{ secrets.GITHUB_TOKEN }}@github.com/balajiudayagiri/Balaji.git
          git push origin gh-pages

        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
